/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import com.formdev.flatlaf.themes.*;

/**
 *
 * @author Sahin
 */
public class MemContigua extends javax.swing.JFrame {

    /**
     * Creates new form MemContigua
     */
    public MemContigua() {

        try{
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            FlatMacDarkLaf.setup();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        initComponents();
        this.setResizable(false);
        tablaProcesos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConfiguración = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        seleccionAjuste = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMemoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSO = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddProceso = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtAddPID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAddTamProc = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtBorProceso = new javax.swing.JTextField();
        btnBorProceso = new javax.swing.JButton();
        encolarProcesos = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnCambiar = new javax.swing.JButton();
        guardarConf = new javax.swing.JButton();
        btnReconf = new javax.swing.JButton();
        panelMemGraf = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelControlProcesos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();
        panelRepresentaciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelTxtRep = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("panelPrincipal"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConfiguración.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de Configuración", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelConfiguración.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Algoritmo de ajuste:");
        panelConfiguración.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        seleccionAjuste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer ajuste", "Siguiente ajuste", "Mejor ajuste", "Peor ajuste" }));
        seleccionAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionAjusteActionPerformed(evt);
            }
        });
        panelConfiguración.add(seleccionAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, -1));

        jLabel3.setText("Tamaño de la memoria:");
        panelConfiguración.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemoriaActionPerformed(evt);
            }
        });
        panelConfiguración.add(txtMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setText("Tamaño del Sistema Operativo:");
        panelConfiguración.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        panelConfiguración.add(txtSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        panelConfiguración.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 10));

        btnAddProceso.setText("Añadir proceso");
        btnAddProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProcesoActionPerformed(evt);
            }
        });
        panelConfiguración.add(btnAddProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel7.setText("PID:");
        panelConfiguración.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        panelConfiguración.add(txtAddPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel8.setText("Tamaño del proceso:");
        panelConfiguración.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        txtAddTamProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddTamProcActionPerformed(evt);
            }
        });
        panelConfiguración.add(txtAddTamProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));
        panelConfiguración.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 200, 20));

        jLabel9.setText("PID: ");
        panelConfiguración.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        panelConfiguración.add(txtBorProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        btnBorProceso.setText("Borrar proceso");
        panelConfiguración.add(btnBorProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        encolarProcesos.setText("Encolar procesos");
        encolarProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encolarProcesosActionPerformed(evt);
            }
        });
        panelConfiguración.add(encolarProcesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelConfiguración.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));
        panelConfiguración.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, 20));

        btnCambiar.setText("Cambiar a memoria paginada");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        panelConfiguración.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 200, -1));

        guardarConf.setText("Guardar configuración");
        guardarConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarConfActionPerformed(evt);
            }
        });
        panelConfiguración.add(guardarConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btnReconf.setText("Reconfigurar");
        btnReconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReconfActionPerformed(evt);
            }
        });
        panelConfiguración.add(btnReconf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        getContentPane().add(panelConfiguración, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 620));

        panelMemGraf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMemGraf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Panel para la memoria gráfica");
        panelMemGraf.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 42, 198, -1));

        getContentPane().add(panelMemGraf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1280, 100));

        panelControlProcesos.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de procesos"));
        panelControlProcesos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Tamaño"
            }
        ));
        jScrollPane1.setViewportView(tablaProcesos);

        panelControlProcesos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, -1));

        getContentPane().add(panelControlProcesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 480, 620));

        panelRepresentaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de visualización"));
        panelRepresentaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(panelTxtRep);

        panelRepresentaciones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 560, 300));

        getContentPane().add(panelRepresentaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 580, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionAjusteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionAjusteActionPerformed

    private void btnAddProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProcesoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddProcesoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtAddTamProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddTamProcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddTamProcActionPerformed

    private void txtMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemoriaActionPerformed

    private void encolarProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encolarProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encolarProcesosActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void guardarConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarConfActionPerformed

    private void btnReconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReconfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReconfActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddProceso;
    public javax.swing.JButton btnBorProceso;
    public javax.swing.JButton btnCambiar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnReconf;
    public javax.swing.JCheckBox encolarProcesos;
    public javax.swing.JButton guardarConf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelConfiguración;
    private javax.swing.JPanel panelControlProcesos;
    public javax.swing.JPanel panelMemGraf;
    private javax.swing.JPanel panelRepresentaciones;
    public javax.swing.JTextPane panelTxtRep;
    public javax.swing.JComboBox<String> seleccionAjuste;
    public javax.swing.JTable tablaProcesos;
    public javax.swing.JTextField txtAddPID;
    public javax.swing.JTextField txtAddTamProc;
    public javax.swing.JTextField txtBorProceso;
    public javax.swing.JTextField txtMemoria;
    public javax.swing.JTextField txtSO;
    // End of variables declaration//GEN-END:variables
}
